services:
  roaster-go:
    build:
      context: ./backend
    container_name: roaster-go
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
    container_name: roaster-frontend
    ports:
      - "8000:80"
    depends_on:
      - roaster-go
    restart: unless-stopped
